version: "3.9"
services:
  db:
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis
  web:
    build: .
    container_name: task-manager-web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    links:
      - sidekiq
  sidekiq:
    build: .
    container_name: task-manager-jobs
    command: bash -c "bundle exec sidekiq"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
volumes:
  mysql:
  bundler_gems:
