default: &default
  adapter: mysql2
  encoding: utf8
  host: db
  username: root
  password: "root"
  pool: 5

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test
